### ISSUE TITLE
CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by mansourehk** [yumeng5/LOTClass#11]
Hi, 
Beautiful paper...
I need to reconstruct your results in order to use them for my purpose.

The installed packages:

```
Package | Version | Latest Version
boto3 | 1.17.30 | 1.17.30
botocore | 1.20.30 | 1.20.30
certifi | 2020.12.5 | 2020.12.5
chardet | 4.0.0 | 4.0.0
click | 7.1.2 | 7.1.2
filelock | 3.0.12 | 3.0.12
idna | 2.10 | 3.1
jmespath | 0.10.0 | 0.10.0
joblib | 1.0.1 | 1.0.1
nltk | 3.5 | 3.5
numpy | 1.20.1 | 1.20.1
packaging | 20.9 | 20.9
pip | 21.0.1 | 21.0.1
pyparsing | 2.4.7 | 2.4.7
python-dateutil | 2.8.1 | 2.8.1
regex | 2021.3.17 | 2021.3.17
requests | 2.25.1 | 2.25.1
s3transfer | 0.3.4 | 0.3.4
sacremoses | 0.0.43 | 0.0.43
sentencepiece | 0.1.95 | 0.1.95
setuptools | 54.1.2 | 54.1.2
six | 1.15.0 | 1.15.0
tokenizers | 0.8.1rc2 | 0.10.1
torch | 1.8.0 | 1.8.0
tqdm | 4.59.0 | 4.59.0
transformers | 3.3.1 | 4.4.1
typing-extensions | 3.7.4.3 | 3.7.4.3
urllib3 | 1.26.4 | 1.26.4
```

I am running it with pycharm-community-2020.3.4 on a Linux OS with one GPU: RTX 2080 Ti

I followed the instructions and ran the following bash:

```
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export CUDA_VISIBLE_DEVICES=0,1

DATASET=agnews
LABEL_NAME_FILE=label_names.txt
TRAIN_CORPUS=train.txt
TEST_CORPUS=test.txt
TEST_LABEL=test_labels.txt
MAX_LEN=200
TRAIN_BATCH=8
ACCUM_STEP=16
EVAL_BATCH=128
GPUS=1
MCP_EPOCH=3
SELF_TRAIN_EPOCH=1

python src/train.py --dataset_dir datasets/${DATASET}/ --label_names_file ${LABEL_NAME_FILE} \
                    --train_file ${TRAIN_CORPUS} \
                    --test_file ${TEST_CORPUS} --test_label_file ${TEST_LABEL} \
                    --max_len ${MAX_LEN} \
                    --train_batch_size ${TRAIN_BATCH} --accum_steps ${ACCUM_STEP} --eval_batch_size ${EVAL_BATCH} \
                    --gpus ${GPUS} \
                    --mcp_epochs ${MCP_EPOCH} --self_train_epochs ${SELF_TRAIN_EPOCH} \
```
However, I get the following error:

```
/.../LOTClass/agnews.sh
Namespace(accum_steps=16, category_vocab_size=100, dataset_dir='datasets/agnews/', dist_port=12345, early_stop=False, eval_batch_size=128, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max_len=200, mcp_epochs=3, out_file='out.txt', self_train_epochs=1.0, test_file='test.txt', test_label_file='test_labels.txt', top_pred_num=50, train_batch_size=8, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Label names used for each class are: {0: ['politics'], 1: ['sports'], 2: ['business'], 3: ['technology']}
Some weights of the model checkpoint at bert-base-uncased were not used when initializing LOTClassModel: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing LOTClassModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing LOTClassModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LOTClassModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias', 'dense.weight', 'dense.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading encoded texts from datasets/agnews/train.pt
Loading texts with label names from datasets/agnews/label_name_data.pt
Loading encoded texts from datasets/agnews/test.pt
Contructing category vocabulary.
  0%|                                                                                                                                                                                                     | 0/62 [00:00<?, ?it/s]
CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
Traceback (most recent call last):
  File "src/train.py", line 66, in <module>
    main()
  File "src/train.py", line 55, in main
    trainer.category_vocabulary(top_pred_num=args.top_pred_num, category_vocab_size=args.category_vocab_size)
  File "/.../LOTClass/src/trainer.py", line 295, in category_vocabulary
    mp.spawn(self.category_vocabulary_dist, nprocs=self.world_size, args=(top_pred_num, loader_name))
  File "/.../LOTClass/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/.../LOTClass/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/.../LOTClass/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 139, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
```
Same goes with "imdb.sh" and "dbpedia.sh".
Moreover, when I execute the "amazon.sh" it gets killed!

```
/.../LOTClass/amazon.sh
Namespace(accum_steps=16, category_vocab_size=100, dataset_dir='datasets/amazon/', dist_port=12345, early_stop=False, eval_batch_size=128, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max_len=200, mcp_epochs=3, out_file='out.txt', self_train_epochs=0.1, test_file='test.txt', test_label_file='test_labels.txt', top_pred_num=50, train_batch_size=8, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Label names used for each class are: {0: ['bad'], 1: ['good']}
Some weights of the model checkpoint at bert-base-uncased were not used when initializing LOTClassModel: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing LOTClassModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing LOTClassModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LOTClassModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias', 'dense.weight', 'dense.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading encoded texts from datasets/amazon/train.pt
Loading texts with label names from datasets/amazon/label_name_data.pt
Reading texts from datasets/amazon/test.txt
Converting texts into tensors.
/.../LOTClass/amazon.sh: line 25:  9306 Killed                  python src/train.py --dataset_dir datasets/${DATASET}/ --label_names_file ${LABEL_NAME_FILE} --train_file ${TRAIN_CORPUS} --test_file ${TEST_CORPUS} --test_label_file ${TEST_LABEL} --max_len ${MAX_LEN} --train_batch_size ${TRAIN_BATCH} --accum_steps ${ACCUM_STEP} --eval_batch_size ${EVAL_BATCH} --gpus ${GPUS} --mcp_epochs ${MCP_EPOCH} --self_train_epochs ${SELF_TRAIN_EPOCH}
```

I appreciate it if you help me on that.

**Comment by yumeng5** [comment]
Hi @mansourehk,

Thanks for letting me know the issue. I realized recently that some multiprocessing functionality in the code may not be compatible with later PyTorch versions (I noticed you were using 1.8.0). Could you try using PyTorch 1.5.0 instead and see if that resolves the issue?

For the amazon dataset issue (process got killed), it is probably because the corpus is larger than the other three datasets, and your machine's memory is not enough to hold the data during corpus pre-processing when using the joblib multiprocessing package. You could try to remove the joblib part as described [here](https://github.com/yumeng5/LOTClass/issues/8#issuecomment-770277041) for the amazon dataset.

Let me know if you continue to have issues.

Best,
Yu

**Comment by mansourehk** [comment]
I change it to PyTorch 1.5.0 and now it is working. Thanks a lot :)
